version: '3.8'

services:
  
  db:
    image: postgres:latest
    restart: unless-stopped
    environment:
        POSTGRES_PASSWORD: password
    volumes:
      - pgdata:/var/lib/postgresql/data
    expose:
      - "5432"
    networks:
      - db

  data:
    image: php:7.0-fpm
    restart: unless-stopped
    volumes:
      - ./data:/var/www/data
    expose:
      - "8080"
    networks:
      - data
      - db

  nginx:
    image: nginx:latest
    restart: unless-stopped
    volumes:
      - ./data:/var/www/data
    ports:
      - "80:80"
      - "443:443"
    networks:
      - data
      - frontend

networks:
  db:
  frontend:
  data:
volumes:
  pgdata: